# Generated by Django 4.2.2 on 2023-06-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_rename_dairy_dairy_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy_entry',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
