# Generated by Django 4.2.2 on 2023-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_dairy_entry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy_entry',
            name='mood',
            field=models.CharField(choices=[('feliz', '😊'), ('triste', '😢'), ('enojado', '😡 '), ('sorprendido', '😮 '), ('confundido', '😕')], default='feliz', max_length=20),
        ),
    ]
