# Generated by Django 4.2.2 on 2023-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hora_comienzo',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hora_limite',
            field=models.TimeField(null=True),
        ),
    ]
