# Generated by Django 4.2.2 on 2023-06-23 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_hora_comienzo_alter_task_hora_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hora_comienzo',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='hora_limite',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
