# Generated by Django 4.2.2 on 2023-06-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_hora_comienzo_alter_task_hora_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hora_comienzo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hora_limite',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
