# Generated by Django 4.2.2 on 2023-06-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_hora_comienzo_alter_task_hora_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_lista',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasklist'),
        ),
    ]
