# Generated by Django 4.2.2 on 2023-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_id_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importancia',
            field=models.CharField(choices=[('Importante', 'Importante'), ('No_Importante', 'No Importante')], max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgencia',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('No_Urgente', 'No Urgente')], max_length=10),
        ),
    ]
